export interface Candidate {
  id: string;
  name: string;
  ward: string;
  category: "mayor" | "councillor";
  hp: number;
  vibe: string;
  quote: string;
  totem: string;
  image: string;
}

export const candidates: Candidate[] = [
  // === MAYORAL ===
  {
    id: "david-trewavas",
    name: "David Trewavas",
    ward: "District-Wide",
    category: "mayor",
    hp: 950,
    vibe: "The Incumbent",
    quote: "Trust and experience matter. I do not make promises I cannot keep.",
    totem: "🦌 Stag",
    image: "/images/candidates/david-trewavas.png",
  },
  {
    id: "kevin-taylor",
    name: "Kevin Taylor",
    ward: "District-Wide",
    category: "mayor",
    hp: 980,
    vibe: "The Enforcer",
    quote: "Rates are broken. We’re funding public services from a model that doesn’t work.",
    totem: "🐂 Bull",
    image: "/images/candidates/kevin-taylor.png",
  },
  {
    id: "john-funnell",
    name: "John Funnell",
    ward: "District-Wide",
    category: "mayor",
    hp: 999,
    vibe: "The Mover & Shaker",
    quote: "Roads, rubbish, and water — those are the core.",
    totem: "🦅 Eagle",
    image: "/images/candidates/john-funnell.png",
  },
  {
    id: "zane-cozens",
    name: "Zane Cozens",
    ward: "District-Wide",
    category: "mayor",
    hp: 999,
    vibe: "The Visionary",
    quote: "This October, you can vote the same and get the same — or vote for change and vote for Zane",
    totem: "🦊 Fox",
    image: "/images/candidates/zane-cozens.png",
  },

  // === MANGAKINO-POUAKANI ===
  {
    id: "marlene-johnson",
    name: "Marlene Johnson",
    ward: "Mangakino-Pouakani",
    category: "councillor",
    hp: 825,
    vibe: "The Guardian",
    quote: "Our community deserves honesty, care and people who follow through.",
    totem: "🐕 Kuri",
    image: "/images/candidates/marlene-johnson.png",
  },
  {
    id: "hope-woodward",
    name: "Hope Woodward",
    ward: "Mangakino-Pouakani",
    category: "councillor",
    hp: 830,
    vibe: "The Warrior",
    quote: "Standing up for community,backing voices and delivering real change",
    totem: "⭐ Whetū",
    image: "/images/candidates/hope-woodward.png",
  },

  // === RURAL ===
  {
    id: "kylie-leonard",
    name: "Kylie Leonard",
    ward: "Rural",
    category: "councillor",
    hp: 820,
    vibe: "The Steward",
    quote: "Strong rural representation matters. I'll stand up for our farming future.",
    totem: "🐄 Cow",
    image: "/images/candidates/kylie-leonard.png",
  },
  {
    id: "rebecca-stafford",
    name: "Rebecca Stafford",
    ward: "Rural",
    category: "councillor",
    hp: 900,
    vibe: "The Analyst",
    quote: "Policy needs clarity. Communities need facts. That’s how we build trust.",
    totem: "🥦 Broccoli",
    image: "/images/candidates/rebecca-stafford.png",
  },

  // === TAUPŌ WARD ===
  {
    id: "richard-cade",
    name: "Richard Cade",
    ward: "Taupō",
    category: "councillor",
    hp: 900,
    vibe: "The Grower",
    quote: "Essential services must be protected — the nice-to-haves can wait.",
    totem: "💜 Lavender",
    image: "/images/candidates/richard-cade.png",
  },
  {
    id: "duncan-campbell",
    name: "Duncan Campbell",
    ward: "Taupō",
    category: "councillor",
    hp: 900,
    vibe: "The Blogger",
    quote: "Transparency. Accountability. Smarter local government. That’s why I’m here.",
    totem: "📓 Notebook",
    image: "/images/candidates/duncan-campbell.png",
  },
  {
    id: "bill-clarke",
    name: "Bill Clarke",
    ward: "Taupō",
    category: "councillor",
    hp: 710,
    vibe: "The Old Hand",
    quote: "Decades in education and community service have taught me what real leadership means.",
    totem: "🌲 Pine",
    image: "/images/candidates/bill-clarke.png",
  },
  {
    id: "nicola-de-lautour",
    name: "Nicola de Lautour",
    ward: "Taupō",
    category: "councillor",
    hp: 860,
    vibe: "The Advocate",
    quote: "I care deeply about our people and our place. It’s time to get things done.",
    totem: "🌿 Fern",
    image: "/images/candidates/nicola-de-lautour.png",
  },
  {
    id: "barry-delany",
    name: "Barry Delany",
    ward: "Taupō",
    category: "councillor",
    hp: 800,
    vibe: "The Businessman",
    quote: "I’ll bring a sharp, community and business-focused lens to every decision.",
    totem: "💼 Briefcase",
    image: "/images/candidates/barry-delany.png",
  },
  {
    id: "david-freeman",
    name: "David Freeman",
    ward: "Taupō",
    category: "councillor",
    hp: 820,
    vibe: "The Pragmatist",
    quote: "I bring common sense, logic and a principled approach to the council table.",
    totem: "⚖️ Scales",
    image: "/images/candidates/david-freeman.png",
  },
  {
    id: "steve-manunui",
    name: "Steve Manunui",
    ward: "Taupō",
    category: "councillor",
    hp: 830,
    vibe: "The Straight Talker",
    quote: "I’m here to listen, represent, and act with common sense and heart.",
    totem: "🪓 Axe",
    image: "/images/candidates/steve-manunui.png",
  },
  {
    id: "steve-punter",
    name: "Steve Punter",
    ward: "Taupō",
    category: "councillor",
    hp: 850,
    vibe: "The Fixer",
    quote: "My hot buttons? Transparency, fairness, and doing things right.",
    totem: "🔧 Spanner",
    image: "/images/candidates/steve-punter.png",
  },
  {
    id: "christine-rankin",
    name: "Christine Rankin",
    ward: "Taupō",
    category: "councillor",
    hp: 800,
    vibe: "The Icon",
    quote: "I work for and am accountable to the voters — not the council.",
    totem: "👓 Glasses",
    image: "/images/candidates/christine-rankin.png",
  },
  {
    id: "rachel-shepherd",
    name: "Rachel Shepherd",
    ward: "Taupō",
    category: "councillor",
    hp: 740,
    vibe: "The Organiser",
    quote: "Clear communication builds trust. That’s how local government should work.",
    totem: "📋 Clipboard",
    image: "/images/candidates/rachel-shepherd.png",
  },
  {
    id: "ann-tweedie",
    name: "Ann Tweedie",
    ward: "Taupō",
    category: "councillor",
    hp: 875,
    vibe: "The Watchful",
    quote: "I’ll bring transparency, smarter planning, and a fierce defence of our uniqueness.",
    totem: "🪶 Feather",
    image: "/images/candidates/ann-tweedie.png",
  },
  {
    id: "belinda-walker",
    name: "Belinda Walker",
    ward: "Taupō",
    category: "councillor",
    hp: 899,
    vibe: "The Advocate",
    quote: "I’m here to grow Taupō’s wellbeing through community, sport, and health equity.",
    totem: "🌸 Blossom",
    image: "/images/candidates/belinda-walker.png",
  },
  {
    id: "yvonne-westerman",
    name: "Yvonne Westerman",
    ward: "Taupō",
    category: "councillor",
    hp: 790,
    vibe: "The Loyalist",
    quote: "I believe in giving back to the place that’s given me so much.",
    totem: "🐟 Trout",
    image: "/images/candidates/yvonne-westerman.png",
  },
  {
    id: "mark-wynyard",
    name: "Mark Wynyard",
    ward: " Outside Taupō Ward ",
    category: "councillor",
    hp: 700,
    vibe: "The Veteran",
    quote: "no quotes",
    totem: "🪵 Log",
    image: "/images/candidates/mark-wynyard.png",
  },
  {
    id: "julie-yeoman",
    name: "Julie Yeoman",
    ward: "Taupō",
    category: "councillor",
    hp: 830,
    vibe: "The Watchdog",
    quote: "Every decision I make will be guided by one principle: keeping our community at the heart of what we do.",
    totem: "🌼 Daisy",
    image: "/images/candidates/julie-yeoman.png",
  },

  // === TŪRANGI/TONGARIRO ===
  {
    id: "raff-rafferty",
    name: "Alan 'Raff' Rafferty",
    ward: "Tūrangi/Tongariro",
    category: "councillor",
    hp: 800,
    vibe: "The Farmer",
    quote: "I’m here to represent our community with honesty and practical experience.",
    totem: "🦌 Tia",
    image: "/images/candidates/alan-rafferty.png",
  },
  {
    id: "david-livingstone",
    name: "David Livingstone",
    ward: "Tūrangi/Tongariro",
    category: "councillor",
    hp: 740,
    vibe: "The Planner",
    quote: "I will stand for all, listen to all, and work for us all.",
    totem: "🧭 Compass",
    image: "/images/candidates/david-livingstone.png",
  },
  {
    id: "sandra-greenslade",
    name: "Sandra Greenslade",
    ward: "Tūrangi/Tongariro",
    category: "councillor",
    hp: 750,
    vibe: "The Carer",
    quote: "Representation that’s local and accountable — that’s what I bring.",
    totem: "🦐 Kōura",
    image: "/images/candidates/sandra-greenslade.png",
  },

  // === MĀORI WARD ===
  {
    id: "wahine-murch",
    name: "Wahine Murch",
    ward: "Maori Ward",
    category: "councillor",
    hp: 890,
    vibe: "The Fighter",
    quote: "Your vote is a vote for a new future — the revolution we need.",
    totem: "🔥 Ahi",
    image: "/images/candidates/wahine-murch.png",
  },
  {
    id: "danny-loughlin",
    name: "Danny Loughlin",
    ward: "Maori Ward",
    category: "councillor",
    hp: 800,
    vibe: "The Networker",
    quote: "The problem with being a Māori Ward Councilor is that you are always busy..",
    totem: "🐍Tuna",
    image: "/images/candidates/danny-loughlin.png",
  },
  {
    id: "ngahuia-foreman",
    name: "Ngahuia Foreman",
    ward: "Maori Ward",
    category: "councillor",
    hp: 750,
    vibe: "The Advocate",
    quote: "I’m not here to be a kūmara or a peacock — I’m here to do the mahi.",
    totem: "🌊 Ngaru",
    image: "/images/candidates/ngahuia-foreman.png",
  },
];


